const AUDIO_ONLY_FORMATS = {
    audio_mp3:  { ext: 'mp3',  container: 'mp3',  audioCodec: 'mp3' },
    audio_m4a:  { ext: 'm4a',  container: 'ipod', audioCodec: 'av_aac' },
    audio_flac: { ext: 'flac', container: 'flac', audioCodec: 'flac16' },
    audio_wav:  { ext: 'wav',  container: 'wav',  audioCodec: 'pcm_s16le' },
    audio_opus: { ext: 'opus', container: 'opus', audioCodec: 'opus' },
    audio_ogg:  { ext: 'ogg',  container: 'ogg',  audioCodec: 'vorbis' },
}

const AUTH_ERROR_PATTERNS = [
    /sign in to confirm/i,
    /not a bot/i,
    /login required/i,
    /private video/i,
    /age-restricted/i,
    /cookies-from-browser/i,
    /use --cookies/i,
    /this video is only available/i,
    /members-only/i,
]

const COOKIE_DOMAINS = [
    'youtube.com',
    'google.com',
    'googleusercontent.com',
    'googlevideo.com',
    'ytimg.com',
]

export function isAudioOnlyFormat(format) {
    return !!AUDIO_ONLY_FORMATS[format]
}

export function getAudioOnlyFormatConfig(format) {
    return AUDIO_ONLY_FORMATS[format] || null
}

export function normalizeYtdlVersion(version) {
    return String(version || '')
        .trim()
        .replace(/^yt-dlp\s+/i, '')
        .replace(/^v/i, '')
}

export function compareYtdlVersions(a, b) {
    const left = normalizeYtdlVersion(a).match(/\d+/g)?.map(Number) || []
    const right = normalizeYtdlVersion(b).match(/\d+/g)?.map(Number) || []
    const max = Math.max(left.length, right.length)

    for (let i = 0; i < max; i += 1) {
        const av = left[i] || 0
        const bv = right[i] || 0
        if (av > bv) return 1
        if (av < bv) return -1
    }
    return 0
}

export function isYtdlUpdateAvailable(currentVersion, latestVersion) {
    if (!currentVersion || !latestVersion) return false
    return compareYtdlVersions(latestVersion, currentVersion) > 0
}

export function isYtdlAuthError(raw) {
    const text = String(raw || '')
    return AUTH_ERROR_PATTERNS.some(pattern => pattern.test(text))
}

export function isYoutubeCookieDomain(domain) {
    const clean = String(domain || '').replace(/^\./, '').toLowerCase()
    return COOKIE_DOMAINS.some(allowed => clean === allowed || clean.endsWith(`.${allowed}`))
}

function cleanCookieField(value) {
    return String(value ?? '').replace(/[\r\n\t]/g, encodeURIComponent)
}

export function formatNetscapeCookie(cookie) {
    const domain = cleanCookieField(cookie.domain || '')
    const includeSubdomains = domain.startsWith('.') ? 'TRUE' : 'FALSE'
    const path = cleanCookieField(cookie.path || '/')
    const secure = cookie.secure ? 'TRUE' : 'FALSE'
    const expiry = Number.isFinite(cookie.expirationDate) ? Math.floor(cookie.expirationDate) : 0
    const name = cleanCookieField(cookie.name || '')
    const value = cleanCookieField(cookie.value || '')

    return [domain, includeSubdomains, path, secure, expiry, name, value].join('\t')
}

export function serializeCookiesToNetscape(cookies) {
    const rows = (Array.isArray(cookies) ? cookies : [])
        .filter(cookie => cookie?.name && cookie?.domain && isYoutubeCookieDomain(cookie.domain))
        .sort((a, b) => {
            const domainCmp = String(a.domain).localeCompare(String(b.domain))
            if (domainCmp !== 0) return domainCmp
            return String(a.name).localeCompare(String(b.name))
        })
        .map(formatNetscapeCookie)

    return [
        '# Netscape HTTP Cookie File',
        '# Generated by Gorex. Do not share this file.',
        ...rows,
        '',
    ].join('\n')
}

