use serde_json::{json, Value};
use std::{fs, path::PathBuf};
use tauri::{AppHandle, Manager, WebviewUrl, WebviewWindow, WebviewWindowBuilder};

use crate::settings;

fn managed_file(app: &AppHandle) -> Result<PathBuf, String> {
    app.path().app_data_dir().map(|path| path.join("youtube-cookies.txt")).map_err(|error| error.to_string())
}

fn login_window(app: &AppHandle, visible: bool) -> Result<WebviewWindow, String> {
    if let Some(window) = app.get_webview_window("youtube-login") {
        if visible { window.show().map_err(|error| error.to_string())?; window.set_focus().map_err(|error| error.to_string())?; }
        return Ok(window);
    }
    let url = url::Url::parse("https://www.youtube.com/").map_err(|error| error.to_string())?;
    let data_dir = app.path().app_data_dir().map_err(|error| error.to_string())?.join("youtube-webview");
    WebviewWindowBuilder::new(app, "youtube-login", WebviewUrl::External(url))
        .title("YouTube — Gorex")
        .inner_size(1100.0, 760.0)
        .data_directory(data_dir)
        .visible(visible)
        .build()
        .map_err(|error| error.to_string())
}

fn is_youtube_domain(domain: &str) -> bool {
    let domain = domain.trim_start_matches('.').to_ascii_lowercase();
    ["youtube.com", "google.com", "googleusercontent.com", "googlevideo.com", "ytimg.com"]
        .iter().any(|allowed| domain == *allowed || domain.ends_with(&format!(".{allowed}")))
}

fn cookie_rows(window: WebviewWindow) -> Result<Vec<(String, String)>, String> {
    let cookies = window.cookies().map_err(|error| error.to_string())?;
    Ok(cookies.into_iter().filter_map(|cookie| {
        let domain = cookie.domain()?.to_owned();
        if !is_youtube_domain(&domain) || cookie.name().is_empty() { return None; }
        let host_subdomains = if domain.starts_with('.') { "TRUE" } else { "FALSE" };
        let clean = |field: &str| field.replace(['\r', '\n', '\t'], "%20");
        let expiry = cookie.expires_datetime().map(|date| date.unix_timestamp().max(0)).unwrap_or(0);
        let row = format!("{}\t{}\t{}\t{}\t{}\t{}\t{}", clean(&domain), host_subdomains, clean(cookie.path().unwrap_or("/")), if cookie.secure().unwrap_or(false) { "TRUE" } else { "FALSE" }, expiry, clean(cookie.name()), clean(cookie.value()));
        Some((cookie.name().to_owned(), row))
    }).collect())
}

async fn relevant_cookies(app: &AppHandle) -> Result<Vec<(String, String)>, String> {
    let window = login_window(app, false)?;
    tokio::task::spawn_blocking(move || cookie_rows(window)).await.map_err(|error| error.to_string())?
}

async fn status(app: &AppHandle) -> Result<Value, String> {
    let cookies = relevant_cookies(app).await?;
    let signed_in = cookies.iter().any(|(name, _)| matches!(name.as_str(), "SID" | "HSID" | "SSID" | "SAPISID" | "APISID" | "LOGIN_INFO" | "__Secure-1PSID" | "__Secure-3PSID"));
    let settings = settings::get_app_settings(app.clone())?;
    Ok(json!({
        "signedIn": signed_in,
        "cookieCount": cookies.len(),
        "managedCookiesFile": managed_file(app)?.to_string_lossy(),
        "cookiesMode": settings["ytdlCookiesMode"].as_str().unwrap_or("auto"),
        "lastExportAt": settings["ytdlAuthLastExportAt"],
    }))
}

#[tauri::command]
pub fn open_youtube_login_window(app: AppHandle) -> Result<(), String> {
    login_window(&app, true).map(|_| ())
}

#[tauri::command]
pub async fn get_youtube_auth_status(app: AppHandle) -> Result<Value, String> {
    status(&app).await
}

#[tauri::command]
pub async fn export_youtube_cookies(app: AppHandle) -> Result<Value, String> {
    let rows = relevant_cookies(&app).await?;
    if rows.is_empty() { return Err("Cookies YouTube/Google не найдены. Сначала войдите в YouTube.".into()); }
    let path = managed_file(&app)?;
    fs::create_dir_all(path.parent().ok_or("Invalid cookie path")?).map_err(|error| error.to_string())?;
    let content = format!("# Netscape HTTP Cookie File\n# Generated by Gorex. Do not share this file.\n{}\n", rows.iter().map(|(_, row)| row.as_str()).collect::<Vec<_>>().join("\n"));
    fs::write(&path, content).map_err(|error| error.to_string())?;
    #[cfg(unix)] {
        use std::os::unix::fs::PermissionsExt;
        fs::set_permissions(&path, fs::Permissions::from_mode(0o600)).map_err(|error| error.to_string())?;
    }
    let exported_at = time::OffsetDateTime::now_utc().format(&time::format_description::well_known::Rfc3339).map_err(|error| error.to_string())?;
    settings::save_app_settings(app.clone(), json!({"ytdlManagedCookiesFile": path, "ytdlCookiesMode":"auto", "ytdlAuthLastExportAt": exported_at}))?;
    status(&app).await
}

#[tauri::command]
pub async fn clear_youtube_auth(app: AppHandle) -> Result<Value, String> {
    if let Some(window) = app.get_webview_window("youtube-login") {
        window.clear_all_browsing_data().map_err(|error| error.to_string())?;
    }
    if let Err(error) = fs::remove_file(managed_file(&app)?) { if error.kind() != std::io::ErrorKind::NotFound { return Err(error.to_string()); } }
    settings::save_app_settings(app.clone(), json!({"ytdlManagedCookiesFile":"", "ytdlAuthLastExportAt":null}))?;
    status(&app).await
}

#[cfg(test)]
mod tests {
    use super::is_youtube_domain;
    #[test]
    fn only_youtube_and_google_cookie_domains_are_exported() {
        assert!(is_youtube_domain(".youtube.com"));
        assert!(is_youtube_domain("accounts.google.com"));
        assert!(!is_youtube_domain("youtube.com.evil.example"));
    }
}
